# Generated by Django 3.2.4 on 2021-06-13 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacao', '0002_auto_20210613_1754'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disciplina',
            name='image',
        ),
        migrations.RemoveField(
            model_name='disciplina',
            name='thumbnail',
        ),
    ]
