# Generated by Django 3.2.4 on 2021-06-13 18:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('avaliacao', '0004_avaliacao_professor'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacao',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to='auth.user'),
            preserve_default=False,
        ),
    ]
