# Generated by Django 3.2.4 on 2021-06-13 18:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacao', '0005_avaliacao_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='avaliacao',
            options={'ordering': ('-date_added',)},
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
