# Generated by Django 3.2.4 on 2021-06-24 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacao', '0007_alter_avaliacao_nota'),
    ]

    operations = [
        migrations.RenameField(
            model_name='avaliacao',
            old_name='semestre',
            new_name='semestre_cronologico',
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='semestre_ita',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
