# Generated by Django 3.2.4 on 2021-06-25 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacao', '0008_auto_20210624_1608'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avaliacao',
            name='semestre_cronologico',
        ),
        migrations.RemoveField(
            model_name='avaliacao',
            name='semestre_ita',
        ),
    ]
